/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Astronaut({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('Astronaut_compressed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['000_Astronaut'].geometry}
        material={materials['Astronaut_mat_35ab8c28-31ed-4d68-94f9-ecfbd445da39']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Astronaut_compressed.glb')
